### PR TITLE
Surface issue propagating errors with Wrap steps

### PR DESCRIPTION
**Pull request by polmiro**
I mentioned running into this issue in gitter and I have been able to write a test to reproduce what I mean. It looks like when a step fails within a `Wrap` the errors are propagated within the `Wrap` steps but not outside of it.

This test does not pass, the operation ends up returning a successful result.

I do not know what would be a good solution for this issue. I'm investigating at the moment but would love some guidance.

### CODE REVIEW

**Comment by apotonick** [comment]
This is by design! The `Wrap` does "protect" the outer caller from the wrapped logic. If you don't want that, use `Nested`. This is documented here: http://trailblazer.to/gems/operation/2.0/api.html#wrap-return-value

**Comment by polmiro** [comment]
In my use case I want wrap a few steps that need to happen in a transaction, but following the same success/failure railways. 

I don't think using Nested could be of any help since the transaction code needs to be wrapped somewhere within the nested operation as well. On the other hand an option `pass_through: true` like the one you mention would fit pretty well.

If you think this makes sense I can work on a PR to add it as an opt-in.

**Comment by apotonick** [comment]
Ok, what are the possible outcomes for the transactions? And what happens if the transaction fails, but all inner steps pass? Etc, etc...

**Comment by polmiro** [comment]
When wrapping a db transaction with a few steps I want to move to the left railway when:
- A step moved to the left railway.
- An rollback exception ocurred which can happen any point in the inside steps or even right after 

I guess the main point is the block being called within Wrap should by default be able to be directly propagated as a truthy/falsy value without the need of comparing with `Pipetree::Railway::Right` or `Pipetree::Railway::Left` which are hidden internals.

I just noticed that `Trailblazer::Operation.Rescue` has a FIXME which I believe exists for the same reason [here](https://github.com/polmiro/trailblazer/blob/master/lib/trailblazer/operation/rescue.rb#L9).

**Pull request closed without merging**
